### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by Tiandishihua** [CVIU-CSU/TCT-InfoNCE#1]
作者，您好！
    您们的这篇文章非常出色，为了更好的学习您们的算法，希望能获取几十个Cervical
Smear Dataset (CSD)数据样本和具体处理数据制作相应数据集格式的步骤，非常感谢您的回复和热情帮助！

**Comment by dilint** [comment]
感谢关注。 我们没有公开CSD数据集的权限，但是根据你的问题，我们在仓库中增加了针对FNAC 2019数据集进行训练的说明。在README.md中我们给出了FNAC-2019的下载链接，原始数据放在base_data中，运行[fnac_split.ipynb](https://github.com/CVIU-CSU/TCT-InfoNCE/blob/main/datatools/fnac/fnac_split.ipynb)进行图片切割，运行[fnac_create_label.ipynb](https://github.com/CVIU-CSU/TCT-InfoNCE/blob/main/datatools/fnac/fnac_create_label.ipynb)进行标签划分，(这里对具体处理数据制作过程做出解答，这些步骤我们已经完成，不需要再执行，CSD数据集的文件组织形式也是类似的，一个WSI一个图像文件夹)。
其他训练的步骤请参考[Train fnac-2019](https://github.com/CVIU-CSU/TCT-InfoNCE#train-fnac-2019)。
